### ISSUE TITLE
Emmet not working properly in ST 3

### ISSUE THREAD

**Issue by piyushmM41** [sergeche/emmet-sublime#623]
hey there! actually i'm facing the same problem in sublime text 3 with emmet that when i use suppose ul>li*6 and hit tab it doesn't work, what to do in this situation ?

**Comment by swashata** [comment]
Hi everyone. I am facing similar issue too. It was working fine with build ST3 Build 3103, but they are changing syntax and scopes right now and I only updated to the latest build 3114 yesterday. Since then, tab auto-completion is not working inside `source.php` files (of course outside `<?php /**/ ?>` blocks. I think for some reason, some php auto-completion plugin is taking over the tab-expand. If I use 
`Ctrl + E`, it works though.

![st3-emmet-issue](https://cloud.githubusercontent.com/assets/1623381/16108770/dab69d0c-33c2-11e6-8310-0c06343c861b.gif)

Please see the attached gif. It used to work fine in build 3103. I am not sure if it is emmet issue or sublime text 3 build 3103 issue.

**Comment by swashata** [comment]
This seems to be solved with 3115 build. For some reason that is not there for download. So I downloaded the latest dev build https://www.sublimetext.com/3dev and it works fine now.

**Comment by piyushmM41** [comment]
actually i shifted from ST3 to ST2 version so there it is working fine !

**Comment by PremedDuck44909** [comment]
I use "a.class#id" but it translate into "a.<class id='id'></class>" Writed at 2017.12.06 emmet - latest, ST - latest, answer as soon as possible pls

**Comment by sergeche** [comment]
Things to check first:
1. Make sure you *actually* installed Emmet: restart ST and check console if it tells that Emmet plugin is loaded.
2. Make sure you document syntax is HTML or any other supported, read https://github.com/sergeche/emmet-sublime#how-to-expand-abbreviations-with-tab-in-other-syntaxes for more info
